Repository Netcracker/qubership-nifi, pull requests merged in 2025-03, with the labels that each got.

#18 fix: fixed shellcheck errors
  nifi-scripts/clear_sensitive_env_vars.sh
  nifi-scripts/common.sh
  nifi-scripts/pre_set_algorithm.sh
  nifi-scripts/qubership_secure.sh
  nifi-scripts/re_encrypt_sensitive_keys.sh
  nifi-scripts/restore_nifi_configurations.sh
  nifi-scripts/secure.sh
  nifi-scripts/set_algorithm.sh
  nifi-scripts/start.sh
  nifi-scripts/start_additional_func.sh
  nifi-scripts/start_consul_app.sh
  nifi-scripts/update_cluster_state_management.sh
Labels: bug, refactor

#25 feat: add unit-test for FetchTableToJson
  .github/linters/.jscpd.json
  .github/linters/.sqlfluff
  .github/linters/sun_checks.xml
  .github/workflows/automatic-pr-labeler.yaml
  .github/workflows/super-linter.yml
  qubership-bundle/qubership-nifi-processors-impl/src/main/java/org/qubership/nifi/processors/FetchTableToJson.java
  qubership-bundle/qubership-nifi-processors-impl/src/test/java/org/qubership/nifi/processors/FetchTableToJsonTest.java
  qubership-bundle/qubership-nifi-processors-impl/src/test/resources/org/qubership/nifi/processors/db_for_test.sql
Labels: enhancement

#28 feat: add PR auto-assignment workflow and configuration
  .github/pr-assigner-config.yml
  .github/workflows/pr-assigner.yml
Labels: enhancement

#27 fix(ci): Update cdxgen.yaml
  .github/linters/actionlint.yml
  .github/workflows/cdxgen.yaml
  .github/workflows/super-linter.yml
Labels: bug

#29 feat: pr-assigner template updated
  .github/workflows/pr-assigner.yml
Labels: enhancement

#30 test: add test for RedisBulkDistributedMapCacheClientService
  .github/linters/config/suppressions.xml
  .github/linters/sun_checks.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api/src/main/java/org/qubership/nifi/service/BulkDistributedMapCacheClient.java
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/src/main/java/org/qubership/nifi/service/RedisBulkDistributedMapCacheClientService.java
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/src/test/java/org/qubership/nifi/service/RedisBulkDistributedMapCacheClientServiceTest.java
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/src/test/java/org/qubership/nifi/service/RedisTestProcessor.java
Labels: enhancement

#33 feat(ci): remove revision property and hard-code versions
  pom.xml
  qubership-bundle/pom.xml
  qubership-bundle/qubership-nifi-processors-impl/pom.xml
  qubership-bundle/qubership-nifi-processors-nar/pom.xml
  qubership-consul/pom.xml
  qubership-consul/qubership-consul-application/pom.xml
  qubership-consul/qubership-consul-util/pom.xml
  qubership-nifi-bulk-redis-service/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/pom.xml
  qubership-nifi-bundle-common/pom.xml
  qubership-nifi-common/pom.xml
  qubership-nifi-db-bundle/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-nar/pom.xml
  qubership-nifi-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-db-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-210/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-214/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-2-220/pom.xml
  qubership-nifi-lookup-services/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service-nar/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service/pom.xml
  qubership-services/pom.xml
  qubership-services/qubership-service-api-nar/pom.xml
  qubership-services/qubership-service-api/pom.xml
  qubership-services/qubership-service-nar/pom.xml
  qubership-services/qubership-service/pom.xml
Labels: enhancement

#34 fix(ci): remove pull_request_target from wf
  .github/workflows/cla.yaml
  .github/workflows/pr-conventional-commits.yaml
  .github/workflows/pr-lint-title.yaml
Labels: bug

#35 test(ci): enable sonar integration
  .github/linters/actionlint.yml
  .github/workflows/docker-build-and-test.yml
  .github/workflows/maven-build-and-test.yml
  .github/workflows/super-linter.yml
  pom.xml
  qubership-bundle/qubership-nifi-processors-impl/src/test/java/org/qubership/nifi/processors/mapping/AbstractDockerBasedTest.java
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/src/test/java/org/qubership/nifi/processors/PostgreSQLBulkLoaderTest.java
Labels: bug, config
