Repository Netcracker/qubership-nifi, pull requests merged in 2025-07, with the labels that each got.

#73 feat: add script for upgrade advisor
  dev/upgrade-advisor/README.md
  dev/upgrade-advisor/upgradeAdvisor.sh
Labels: enhancement

#75 fix(ci): add missing permissions to cdxgen and maven-release workflows
  .github/workflows/cdxgen.yaml
  .github/workflows/maven-release.yaml
Labels: bug

#78 chore: remove snapshot from version before release
  pom.xml
  qubership-bundle/pom.xml
  qubership-bundle/qubership-nifi-processors-impl/pom.xml
  qubership-bundle/qubership-nifi-processors-nar/pom.xml
  qubership-consul/pom.xml
  qubership-consul/qubership-consul-application/pom.xml
  qubership-consul/qubership-consul-util/pom.xml
  qubership-nifi-bulk-redis-service/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/pom.xml
  qubership-nifi-bundle-common/pom.xml
  qubership-nifi-common/pom.xml
  qubership-nifi-db-bundle/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-nar/pom.xml
  qubership-nifi-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-db-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-210/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-214/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-2-220/pom.xml
  qubership-nifi-lookup-services/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service-nar/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service/pom.xml
  qubership-services/pom.xml
  qubership-services/qubership-service-api-nar/pom.xml
  qubership-services/qubership-service-api/pom.xml
  qubership-services/qubership-service-nar/pom.xml
  qubership-services/qubership-service/pom.xml
Labels: config

#77 test(ci): add cluster autotest
  .github/actions/run-conf-restore-test/action.yml
  .github/actions/run-newman-tests/action.yml
  .github/actions/run-nifi-tests-generic/action.yaml
  .github/actions/run-nifi-tests-oidc/action.yaml
  .github/actions/run-nifi-tests-plain/action.yml
  .github/actions/run-nifi-tests-tls/action.yaml
  .github/collections/Setup_Cluster_Access_Policies.postman_collection.json
  .github/docker/cluster-statefulset/docker-compose.yaml
  .github/docker/cluster/docker-compose.yaml
  .github/docker/oidc/docker-compose.yaml
  .github/docker/plain/docker-compose.yaml
  .github/docker/tls/docker-compose.yaml
  .github/workflows/docker-build-and-test.yml
  .github/workflows/sh/nifi-gen-certs.sh
  .github/workflows/sh/nifi-lib.sh
  docs/administrator-guide.md
Labels: documentation, config

#82 docs: added description CONSUL_ACL_TOKEN
  docs/administrator-guide.md
Labels: documentation

#83 fix: fix upgradeAdvisor script
  dev/upgrade-advisor/README.md
  dev/upgrade-advisor/upgradeAdvisor.sh
Labels: bug, documentation
