Repository Netcracker/qubership-nifi, pull requests merged in 2025-05, with the labels that each got.

#42 feat: added docker test for nifi in oidc mode
  .github/actions/run-nifi-tests-oidc/action.yaml
  .github/collections/Setup_Access_Policies.postman_collection.json
  .github/configuration/keycloak/nifi-test-realm.json
  .github/docker/oidc/docker-compose.yaml
  .github/workflows/docker-build-and-test.yml
  .github/workflows/sh/nifi-lib.sh
Labels: enhancement

#43 fix: using consul_pid variable
  nifi-scripts/start.sh
Labels: bug

#44 fix: fixed operator error in secure.sh
  nifi-scripts/secure.sh
Labels: bug

#45 docs: update readme and documents
  .github/workflows/docker-build-and-test.yml
  .github/workflows/maven-build-and-test.yml
  .gitignore
  README.md
  dev/plain/.env
  dev/plain/docker-compose.yml
  docs/administrator-guide.md
  docs/drawio/nifi-overview.drawio
  docs/images/nifi-overview.png
  docs/installation-guide.md
  docs/user-guide.md
Labels: documentation

#46 docs: update overview image
  docs/drawio/nifi-overview.drawio
  docs/images/nifi-overview.png
Labels: documentation

#51 feat: add docker e2e autotest
  .github/actions/run-conf-restore-test/action.yml
  .github/actions/run-newman-tests/action.yml
  .github/actions/run-nifi-tests-oidc/action.yaml
  .github/actions/run-nifi-tests-plain/action.yml
  .github/actions/run-nifi-tests-tls/action.yaml
  .github/collections/Check_Processor_API.postman_collection.json
  .github/collections/Global_Vars.postman_globals.json
  .github/collections/NiFi_AT_TLS.json.postman_environment
  .github/collections/NiFi_E2E_API_Tests.postman_collection.json
  .github/docker/oidc/docker-compose.yaml
  .github/super-linter.env
  .github/workflows/docker-build-and-test.yml
  .github/workflows/sh/nifi-lib.sh
  README.md
  dev/plain/docker-compose.yml
  docs/administrator-guide.md
  docs/installation-guide.md
Labels: enhancement
