Repository Netcracker/qubership-nifi, pull requests merged in 2025-06, with the labels that each got.

#57 feat: moving nifi timeout properties over consul
  qubership-consul/qubership-consul-util/src/main/resources/nifi_default.properties
  qubership-consul/qubership-consul-util/src/main/resources/nifi_internal.properties
Labels: enhancement

#56 feat: add script for export update
  dev/update-scripts-2.0/README.md
  dev/update-scripts-2.0/increaseNiFiVersionUpdate.sh
  dev/update-scripts-2.0/updateNiFiFlow.sh
  dev/update-scripts-2.0/updateNiFiVerNarConfig.json
Labels: enhancement

#64 fix(ci): add maven project names to all published artifacts
  qubership-consul/qubership-consul-util/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/pom.xml
  qubership-nifi-bundle-common/pom.xml
  qubership-nifi-common/pom.xml
  qubership-services/qubership-service-api-nar/pom.xml
  qubership-services/qubership-service-api/pom.xml
  qubership-services/qubership-service-nar/pom.xml
  qubership-services/qubership-service/pom.xml
Labels: bug

#66 fix(ci): fix profile handling in maven-release workflow v1
  .github/workflows/maven-release.yaml
Labels: bug

#71 chore: update version before release 1.0.3
  pom.xml
  qubership-bundle/pom.xml
  qubership-bundle/qubership-nifi-processors-impl/pom.xml
  qubership-bundle/qubership-nifi-processors-nar/pom.xml
  qubership-consul/pom.xml
  qubership-consul/qubership-consul-application/pom.xml
  qubership-consul/qubership-consul-util/pom.xml
  qubership-nifi-bulk-redis-service/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-api/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis-nar/pom.xml
  qubership-nifi-bulk-redis-service/qubership-nifi-bulk-redis/pom.xml
  qubership-nifi-bundle-common/pom.xml
  qubership-nifi-common/pom.xml
  qubership-nifi-db-bundle/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-nar/pom.xml
  qubership-nifi-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-db-deps/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-210/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-1-214/pom.xml
  qubership-nifi-deps/qubership-nifi-h2-deps-2-2-220/pom.xml
  qubership-nifi-lookup-services/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service-nar/pom.xml
  qubership-nifi-lookup-services/qubership-nifi-lookup-service/pom.xml
  qubership-services/pom.xml
  qubership-services/qubership-service-api-nar/pom.xml
  qubership-services/qubership-service-api/pom.xml
  qubership-services/qubership-service-nar/pom.xml
  qubership-services/qubership-service/pom.xml
Labels: config
