Repository Netcracker/qubership-nifi, pull requests merged in 2025-02, with the labels that each got.

#2 feat(ci): Added common workflows.
  .github/auto-labeler-config.yaml
  .github/release-drafter-config.yml
  .github/workflows/automatic-pr-labeler.yaml
  .github/workflows/cla.yaml
  .github/workflows/pr-conventional-commits.yaml
  .github/workflows/pr-lint-title.yaml
  .github/workflows/prettier.yaml
  .github/workflows/profanity-filter.yaml
  .prettierignore
Labels: enhancement

#3 chore: Add CODEOWNERS file
  .github/CODEOWNERS
Labels: documentation

#5 feat(ci): fix artifacts copy to top
  qubership-assembly/pom.xml
Labels: enhancement

#7 fix: update curl version in Dockerfile
  Dockerfile
Labels: bug

#10 feat(ci): add super-linter.yml
  .github/workflows/prettier.yaml
  .github/workflows/super-linter.yml
Labels: enhancement

#9 fix: upgrade jetty, junit, testcontainers libs
  Dockerfile
  pom.xml
  qubership-bundle/pom.xml
  qubership-bundle/qubership-nifi-processors-impl/pom.xml
  qubership-bundle/qubership-nifi-processors-impl/src/test/resources/testcontainers.properties
  qubership-nifi-bulk-redis-service/pom.xml
  qubership-nifi-bundle-common/pom.xml
  qubership-nifi-db-bundle/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/pom.xml
  qubership-nifi-db-bundle/qubership-nifi-db-processors-impl/src/test/resources/testcontainers.properties
  qubership-nifi-lookup-services/qubership-nifi-lookup-service/pom.xml
  qubership-services/pom.xml
  qubership-services/qubership-service/pom.xml
Labels: bug

#13 feat: upgrade maven nar plugin to the latest version
  pom.xml
Labels: enhancement

#14 feat: Added maven-release workflow
  .github/workflows/maven-release.yaml
Labels: enhancement

#16 feat(ci): enhance maven-release workflow to support dynamic dry-run o…
  .github/workflows/maven-release.yaml
Labels: enhancement

#17 fix: change script name
  Dockerfile
  nifi-scripts/clear_sensitive_env_vars.sh
  nifi-scripts/common.sh
  nifi-scripts/logging_api.sh
  nifi-scripts/pre_set_algorithm.sh
  nifi-scripts/qubership_secure.sh
  nifi-scripts/re_encrypt_sensitive_keys.sh
  nifi-scripts/restore_nifi_configurations.sh
  nifi-scripts/secure.sh
  nifi-scripts/set_algorithm.sh
  nifi-scripts/start.sh
  nifi-scripts/start_additional_func.sh
  nifi-scripts/start_consul_app.sh
  nifi-scripts/update_cluster_state_management.sh
Labels: bug

#24 fix(ci): publish to mvn central
  pom.xml
  qubership-consul/pom.xml
Labels: bug
